spring:
  application:
    name: GroupUp

  datasource:
    url: jdbc:postgresql://localhost:5432/unicircleDB
    username: postgres
    password: sakai@200
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          fetch_size: 50

jwt:
  secret-key: as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl